### PR TITLE
Add rd_kafka_consumer_close()

### PR DESCRIPTION
**Pull request by fox0430**

### CODE REVIEW

**Comment by fox0430** [comment]
@walkre-niboshi 

Please watch this repo.

**Comment by walkre-niboshi** [comment]
@fox0430 

Should I merge this PR?

**Comment by fox0430** [comment]
Yes. please

**Comment by fox0430** [comment]
@walkre-niboshi

**Comment by fox0430** [comment]
@walkre-niboshi Thanks

**Comment by masa2el** [comment]
[Banner](http://darksouls2.wikidot.com/%0a/connect.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](http://darksouls2.wikidot.com/%0a/connect.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
0xPetra, @dcbuild3r, @swimricky, @alchemyp, @recursion128, @crypto-malloc, @ui0x, @qope, @diego-G, @mempirate, @d1k0b3o, @antontroskie, @vafanassieff, @pantaovay, @sham789, @coconut49, @bryanapperson, @antx-code, @malzzz, @avhz, @philipmoniaga, @iKausik, @KABBOUCHI, @jraymond96, @Iceapinan, @bixia, @toursonlk, @A1igator, @onsails, @trissiswaifu, @defewit, @wsdt, @orpheuslummis, @0xfinder, @TenviLi, @parastrom, @pkingc33, @isvforall, @marko-lazic, @skvorn, @yanbowen1994, @Neronjust2017, @banchou0531, @TimvanScherpenzeel, @khssnv, @fullkomnun, @ferrell-code, @TrNix0126, @incrypto32, @kodjunkie

**Pull request merged**
